-- MySQL Script generated by MySQL Workbench
-- 11/07/16 17:23:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdlespool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdlespool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdlespool` DEFAULT CHARACTER SET utf8 ;
USE `bdlespool` ;

-- -----------------------------------------------------
-- Table `bdlespool`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Usuario` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NULL,
  `Apellidos` VARCHAR(20) NULL,
  `Correo` VARCHAR(150) NULL,
  `Telefono` VARCHAR(10) NULL,
  `Direccion` TEXT(150) NULL,
  `Contraseña` VARCHAR(10) NULL,
  `Val_Contraseña` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlespool`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Orden` (
  `Id_Orden` INT NOT NULL AUTO_INCREMENT,
  `N` INT NULL,
  `Fecha` DATE NULL,
  `Orden` VARCHAR(45) NULL,
  `SubTotal` INT NULL,
  `DescTotal` INT NULL,
  `Total` INT NULL,
  `Usuario_Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Orden`, `Usuario_Id_Usuario`),
  INDEX `fk_Orden_Usuario1_idx` (`Usuario_Id_Usuario` ASC),
  CONSTRAINT `fk_Orden_Usuario1`
    FOREIGN KEY (`Usuario_Id_Usuario`)
    REFERENCES `bdlespool`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlespool`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Categoria` (
  `IdCategoria` INT NOT NULL,
  `Descripcion` TEXT(150) NULL,
  PRIMARY KEY (`IdCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlespool`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Productos` (
  `IdProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Precio` INT NULL,
  `Descripcion` TEXT(150) NULL,
  `Tamaño` VARCHAR(20) NULL,
  `Registro` VARCHAR(10) NULL,
  `Categoria_IdCategoria` INT NOT NULL,
  `Administrador_Id_TipAdministrador` INT NOT NULL,
  PRIMARY KEY (`IdProductos`, `Categoria_IdCategoria`, `Administrador_Id_TipAdministrador`),
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_IdCategoria` ASC),
  INDEX `fk_Productos_Administrador1_idx` (`Administrador_Id_TipAdministrador` ASC),
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_IdCategoria`)
    REFERENCES `bdlespool`.`Categoria` (`IdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Administrador1`
    FOREIGN KEY (`Administrador_Id_TipAdministrador`)
    REFERENCES `bdlespool`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlespool`.`Detalle_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Detalle_orden` (
  `IdDetalle` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Cantidad` INT NULL,
  `Precio` INT NULL,
  `SubTotal` INT NULL,
  `Total` INT NULL,
  `Orden_Id_Orden` INT NOT NULL,
  `Productos_IdProductos` INT NOT NULL,
  PRIMARY KEY (`IdDetalle`, `Orden_Id_Orden`, `Productos_IdProductos`),
  INDEX `fk_Detalle_orden_Orden1_idx` (`Orden_Id_Orden` ASC),
  INDEX `fk_Detalle_orden_Productos1_idx` (`Productos_IdProductos` ASC),
  CONSTRAINT `fk_Detalle_orden_Orden1`
    FOREIGN KEY (`Orden_Id_Orden`)
    REFERENCES `bdlespool`.`Orden` (`Id_Orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_orden_Productos1`
    FOREIGN KEY (`Productos_IdProductos`)
    REFERENCES `bdlespool`.`Productos` (`IdProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlespool`.`Inicio de sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlespool`.`Inicio de sesion` (
  `Id_inicio` INT NOT NULL AUTO_INCREMENT,
  `Correo` VARCHAR(150) NOT NULL,
  `Contraseña` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_inicio`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
